sudo: required

services:
  - docker

before_install:
  - docker build -t patkruk/docker-react -f Dockerfile.dev .

script:
  - docker run patkruk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-321864403338
  bucket_path: docker-react
  on:
    branch: master